import fs from 'fs';
import path from 'path';

const detailedTopicsDir = 'e:/Projects/aws-ai-practitioner/detailed_topics';
const topicsDataFile = 'e:/Projects/aws-ai-practitioner/src/data/topicsData.js';

const domainMapping = {
  '01_exam_metrics.md': 'General Mechanics',
  '02_foundational_concepts.md': 'Domain 1 & 2: Foundational Concepts / Neural Networks',
  '03_nlp.md': 'Domain 1 & 3: NLP & AWS Speech/Language APIs',
  '04_traditional_ml.md': 'Domain 1: Machine Learning Paradigms',
  '05_traditional_ml_algorithms.md': 'Domain 1: Machine Learning Paradigms',
  '06_neural_networks_and_deep_learning.md': 'Domain 1 & 2: Neural Networks & Activation Functions',
  '07_parameters_vs_hyperparameters.md': 'Domain 1: Machine Learning Parameters & HPO',
  '08_model_evaluation_metrics.md': 'Domain 1: Model Evaluation Metrics',
  '09_data_integration_lakes_and_query_services.md': 'Domain 1 & 5: Data Integration & Security',
  '10_high_performance_compute_and_storage.md': 'Domain 1 & 3: Compute, Storage & SageMaker Endpoints',
  '11_foundation_models_and_llms.md': 'Domain 2: Foundation Models & Transformers',
  '12_prompt_engineering_techniques.md': 'Domain 3: Prompt Engineering Design',
  '13_rag_and_agentic_architectures.md': 'Domain 3: Advanced RAG & Vector Search',
  '14_aws_ai_and_ml_services.md': 'Domain 3 & 5: AWS Managed AI Catalog & Security',
  '15_responsible_ai_and_explainability.md': 'Domain 4: Responsible AI & Model Explainability',
  '16_compliance_security_governance.md': 'Domain 5: Compliance & Security Scoping Matrix',
  '17_prompt_injection_and_mitigations.md': 'Domain 3 & 5: GenAI Threat Mitigations & Guardrails',
  '18_governance_and_drift.md': 'Domain 5: AI Governance & Model Drift',
  '19_analytics_security_financial_governance.md': 'Domain 3 & 5: Advanced Analytics & Security Governance'
};

function parseFile(fileName, id) {
  const filePath = path.join(detailedTopicsDir, fileName);
  const rawContent = fs.readFileSync(filePath, 'utf8');
  
  // Title is the first header line
  const lines = rawContent.split('\n');
  let title = '';
  for (let line of lines) {
    if (line.startsWith('# ')) {
      title = line.replace(/^#\s+[^\w]*\s*/, '').trim();
      break;
    }
  }
  
  // Domain mapping
  const domain = domainMapping[fileName] || 'General';
  
  // Extract summary: first paragraph of text that is not a header, blockquote, or empty
  let summary = '';
  for (let line of lines) {
    const cleanLine = line.trim();
    if (cleanLine && !cleanLine.startsWith('#') && !cleanLine.startsWith('>') && !cleanLine.startsWith('*') && !cleanLine.startsWith('-') && !cleanLine.startsWith('`')) {
      summary = cleanLine;
      break;
    }
  }
  if (summary.length > 200) {
    summary = summary.substring(0, 200) + ' ...';
  }
  
  // Extract gotchas
  // We look for blockquotes (> [!WARNING], > [!CAUTION], > [!IMPORTANT]) and extract their bold parts + content
  const gotchas = [];
  let inBlockquote = false;
  let currentGotcha = [];
  
  for (let line of lines) {
    if (line.startsWith('>')) {
      inBlockquote = true;
      const content = line.replace(/^>\s*/, '').trim();
      // Skip the alert type tags like [!WARNING], [!CAUTION], [!IMPORTANT], [!NOTE], [!TIP]
      if (!content.startsWith('[!')) {
        currentGotcha.push(content);
      }
    } else {
      if (inBlockquote && currentGotcha.length > 0) {
        const fullGotcha = currentGotcha.join(' ').trim();
        // Check if it looks like a gotcha (contains bold start, or contains gotcha/warning/trap/hazard/risk/penalty/latency)
        if (fullGotcha.includes('**') || /gotcha|warning|caution|hazard|trap|risk|penalty|latency/i.test(fullGotcha)) {
          gotchas.push(fullGotcha);
        }
        currentGotcha = [];
      }
      inBlockquote = false;
    }
  }
  if (inBlockquote && currentGotcha.length > 0) {
    const fullGotcha = currentGotcha.join(' ').trim();
    if (fullGotcha.includes('**') || /gotcha|warning|caution|hazard|trap|risk|penalty|latency/i.test(fullGotcha)) {
      gotchas.push(fullGotcha);
    }
  }
  
  return {
    id,
    file: fileName,
    title,
    domain,
    content: rawContent,
    summary,
    gotchas: gotchas.filter(g => g.length > 0)
  };
}

function run() {
  const files = fs.readdirSync(detailedTopicsDir)
    .filter(f => f.endsWith('.md'))
    .sort();
    
  const modules = files.map((file, index) => parseFile(file, index + 1));
  
  const jsContent = `// This file is system-generated by parse_topics.js
// Do not edit directly.

export const modules = ${JSON.stringify(modules, null, 2)};
`;

  fs.writeFileSync(topicsDataFile, jsContent, 'utf8');
  console.log(`Generated ${modules.length} modules inside topicsData.js successfully.`);
}

run();
